# Generated by Django 4.1.6 on 2023-03-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_text_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
    ]
